services:

  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092" 
      - "29092:29092"   
      - "9093:9093"
    healthcheck:
      test: ["CMD", "bash", "-c", "nc -z localhost 29092"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: '0@kafka:9093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks: [test-net]

  db:
    image: postgres:latest 
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    networks: [test-net]

  backend:
    build: ./JavaMainService
    ports: ["8080:8080"]
    networks: [test-net]
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
  
  # tg-client:
  #   build: ./PythonTgClient
  #   depends_on:
  #     - kafka
  #   networks: [test-net]

  mail-client:
    build: ./PythonMailingService
    depends_on:
      kafka:
        condition: service_healthy
    networks: [test-net]
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    networks: [test-net]
    ports:
      - "80:80"

volumes:
  pgdata:

networks:
  test-net:
    driver: bridge
